<?php

/**
 * 联系方式小部件
 */

namespace app\components;

use app\helpers\TMSHelper;
use yii\base\Widget;

class ContactWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $contactInfo =  TMSHelper::getContactInfo();
        $res = [];
        foreach ($contactInfo as $k=>$v){
            $res[$v['name']] = $v['content'];
        }
        return $this->render('contact',['contactInfo'=>$res]);
    }

}